### ISSUE TITLE
Add Purescript type generation for PlutusTx.Ratio

### ISSUE THREAD

**Issue by stanislav-az** [input-output-hk/plutus#4019]
## Area

[O] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[X] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[O] *Marlowe* Related to Marlowe
[O] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like
Generate a type for Ratio in plutus types [declarations](https://github.com/input-output-hk/plutus/blob/33d1f7029c58b7c6e3687064f7fb9a76978e0c18/plutus-pab/src/Plutus/PAB/Run/PSGenerator.hs#L79) by adding something like
`(equal <*> (genericShow <*> mkSumType)) (Proxy @(Ratio A))`

## Describe alternatives you've considered

Making types conversions between the Ratio type and some other wrapper.

## Additional context / screenshots

Generating this Purescript type requires some changes to constructor, for now generation does not work because generated module cannot be parsed:
```
Error found:
at generated/PlutusTx/Ratio.purs:21:5 - 21:7 (line 21, column 5 - line 21, column 7)

  Unable to parse module:
  Unexpected token ':%'
```

**Comment by ak3n** [comment]
Could you please try 409ef647525f23aa40c07db1fa8e11c71b274f84?

**Comment by stanislav-az** [comment]
> Could you please try 409ef64?

Okay, we will try to use this bridge part

**Comment by olgaklimenko** [comment]
Bridge hasn't help. The error is:

![image](https://user-images.githubusercontent.com/11536292/135395755-878f4241-191d-4f92-83ff-c12bebb48e88.png)

**Comment by ak3n** [comment]
Will take a look, thanks!

**Comment by ak3n** [comment]
The idea behind bridge is that it will translate `PlutusTx.Ratio` Haskell type into `Data.Ratio` Purescript type. So you should use `Data.Ratio` in your Purescript code.

I'm not sure yet how it will work for server/client communication. Might need some fixes.

**Comment by stanislav-az** [comment]
The problem here is we need to make some fields of our generated types (e.g. [Percentage](https://github.com/input-output-hk/plutus-use-cases/blob/e546b8b2569a89f1cfe4abd913f69d37458d7f56/MetaLamp/nft-marketplace/src/Plutus/Types/Percentage.hs#L17)) of type `:: PlutusTx.Ratio.Ratio Integer`. 
That means we need to import PlutusTx.Ratio in some haskell module. When that module is generated, there is error during Purescript compilation:
![image](https://user-images.githubusercontent.com/43969704/135428904-debfe3ff-e771-4fec-b620-9f5d76efd46a.png)

**Comment by ak3n** [comment]
Oh, right, sorry, please try 3c183d0072d7fabe78cccb4c65dd737dbd4a5a6c. I have fixed the bridge. I hope it will help.

**Comment by olgaklimenko** [comment]
Yes, I tried to use `PlutusTx.Ratio` instead of `Data.Ratio` too. Still the same error. 

I created [commit in our repo](https://github.com/input-output-hk/plutus-use-cases/commit/20303f3124b6464e86574a0fbb01ef73c571b588) with comments to show what exactly we have done to produce that error.

**Comment by ak3n** [comment]
Will take a look, thanks!

**Comment by stanislav-az** [comment]
I think we need the same implementation as it is done for `PlutusTx.AssocMap`:
* There is a bridge for the [type](https://github.com/input-output-hk/plutus/blob/5e409452303b2bd9a5381b0f97f9a47edd69767d/playground-common/src/PSGenerator/Common.hs#L205)
* There is a Purescript [module](https://github.com/input-output-hk/plutus/blob/master/web-common/src/PlutusTx/AssocMap.purs)

**Comment by ak3n** [comment]
80e39965f1bd2232fced11f62d71ad58b79f0715 should help

**Comment by ak3n** [comment]
@stanislav-az might be true as there is no default `Decode` and `Encode` instances for `Data.Ratio`.

**Comment by ak3n** [comment]
I have tried to introduce a proper wrapper for `PlutusTx.Ratio` in e14a76116f7818c4da7a562a6044fb991f903b9b. Please test.
